just_LR_preds_no_Illumina:
	./analyze_cancer_data.pl


illum_TP_uniq_FP:
	./analyze_Illum_as_TP_unique_as_FP.pl either
	./analyze_Illum_as_TP_unique_as_FP.pl arriba,starF
	./analyze_Illum_as_TP_unique_as_FP.pl arriba
	./analyze_Illum_as_TP_unique_as_FP.pl starF


clean:
	./cleanMe.sh

