just_LR_preds_no_Illumina:
	./analyze_cancer_data.pl


incl_extra_starF_supported_in_truth_by_Illum:
	./analyze_cancer_data.pl --extra_true $(PWD)/StarFusion_Illumina_supported_fusions.tsv


clean:
	./cleanMe.sh

