
incl_extra_starF_supported_in_truth:
	./analyze_cancer_data.pl --extra_true $(PWD)/StarFusion_Illumina_supported_fusions.tsv

just_preds_no_Illumina:
	./analyze_cancer_data.pl


clean:
	./cleanMe.sh

